name: byu_pytest_utils Prebuild

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  markdowndata_prebuild:
    uses: BYU-CS-Course-Ops/utils/.github/workflows/poetry_prebuild.yaml@main
    with:
      pypi_package: "byu_pytest_utils"
